# fly.toml app configuration file generated for billowing-resonance-6555 on 2023-08-02T12:35:49+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "billowing-resonance-6555"
primary_region = "sin"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
